version: '3.8'

services:
  keycloak_db:
    image: postgres:16
    restart: always
    ports:
      - '5433:5433'
    volumes:
      - /srv/keycloak/data/postgres16:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${POSTGRES_USER:-keycloak}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-eX4mP13p455w0Rd}

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.1
    restart: on-failure:3
    ports:
      - '8282:8080'
    environment:
      KC_DB: postgres
      KC_DB_URL: 'jdbc:postgresql://keycloak_db:5433/keycloak'
      KC_DB_USERNAME: ${POSTGRES_USER:-keycloak}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD:-eX4mP13p455w0Rd}
      KC_DB_SCHEMA: public
      KC_HOSTNAME: ${KC_HOSTNAME:-localhost}
      KC_HTTP_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-eX4mP13p455w0Rd}
      KEYCLOAK_IMPORT: /opt/keycloak/data/import/realm-export.json
      # KC_PROXY_HEADERS: xforwarded
    command: start --verbose --optimized
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
    depends_on:
      - keycloak_db
  
      
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY:-UsEr_y8b-DSq-C2K-t32} $
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY:-y8b-DSq-C2K-t32}
    command: server ~/minio --console-address :9090
    ports:
      - '9090:9090'
      - '9000:9000'
    volumes:
      - minio-data:/minio

volumes:
  postgres_data:
  minio-data: