version: '3'

services:
  # text-correction-service:
  #   build:
  #     context: .
  #     dockerfile: animal-publciation-service/Dockerfile
  #   ports:
  #     - "81:81"


  # notification-service:
  #   build:
  #     context: .
  #     dockerfile: notification-service/NotificationService/Dockerfile
  #   ports:
  #     - "82:82"
    
    
  document-processing-service:
    build:
      context: .
      dockerfile: document-processing-service/Dockerfile
    ports:
      - "83:83"

  # gateway:
  #   build:
  #     context: .
  #     dockerfile: api-gateway/Dockerfile
  #   ports:
  #     - "80:80"

  db:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: filesdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: uzorov
    ports:
      - "5432:5432"

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    command: server ~/minio --console-address :9090
    ports:
      - '9090:9090'
      - '9000:9000'
    volumes:
      - minio-data:/minio



volumes:
  postgres_data:
  minio-data:
