version: '3'

services:

  # keycloak:
  #   image: quay.io/keycloak/keycloak:23.0.1
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - KEYCLOAK_ADMIN=admin
  #     - KEYCLOAK_ADMIN_PASSWORD=admin
  #   command:
  #     - "start-dev"

  # ai-service:
  #   build:
  #     context: .
  #     dockerfile: ai-service/Dockerfile
  #   ports:
  #     - "84:84"

  # notification-service:
  #   build:
  #     context: .
  #     dockerfile: notification-service/NotificationService/Dockerfile
  #   ports:
  #     - "82:82"
    
  # db:
  #   image: postgres:16-alpine
  #   container_name: postgres
  #   environment:
  #     POSTGRES_DB: filesdb
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: uzorov
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

  # document-processing-service:
  #   build:
  #     context: .
  #     dockerfile: document-processing-service/Dockerfile
  #   ports:
  #     - "83:83"
  #   environment:
  #     POSTGRES_DB: filesdb
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: uzorov
  #     POSTGRES_HOST: 87.242.86.68
  #     POSTGRES_PORT: 5432
    # depends_on:
    #   - db


  web-interface:
    build:
      context: .
      dockerfile: UI/Dockerfile
    ports:
      - "8000:8000"

  # gateway:
  #   build:
  #     context: .
  #     dockerfile: api-gateway/Dockerfile
  #   ports:
  #     - "81:81"

  # db:
  #   image: postgres:16-alpine
  #   container_name: postgres
  #   environment:
  #     POSTGRES_DB: filesdb
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: uzorov
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data  
  #   entrypoint:
  #     - /entrypoint.sh

  # minio:
  #   image: minio/minio:latest
  #   container_name: minio
  #   environment:
  #     - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
  #     - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
  #   command: server ~/minio --console-address :9090
  #   ports:
  #     - '9090:9090'
  #     - '9000:9000'
  #   volumes:
  #     - minio-data:/minio

# volumes:
#   postgres_data:
  # minio-data:
