services:

  ai-service:
    build:
      context: .
      dockerfile: ai-service/Dockerfile
    image: uzorovkirill/correct-text-ai:latest
    ports:
      - "84:84"

  document-processing-service:
    build:
      context: .
      dockerfile: document-processing-service/Dockerfile
    image: uzorovkirill/document-processing-service:latest
    ports:
      - "83:83"
    environment:
      POSTGRES_DB: filesdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: uzorov
      POSTGRES_HOST: 87.242.86.68
      POSTGRES_PORT: 5432
      MINIO_HOST: 87.242.86.68:9000
      MINIO_ACCESS_KEY: UsEr_y8b-DSq-C2K-t32
      MINIO_SECRET_KEY: y8b-DSq-C2K-t32
      HOST_IP: 192.168.0.11


  gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    image: uzorovkirill/api-gateway:latest
    environment:
      - HOST_IP=192.168.0.11  
      - DOCUMENT_SERVICE_PORT=83
      - TEXT_CORRECTION_SERVICE_PORT=84
    ports:
      - "81:81"
    depends_on:
      - document-processing-service
      - ai-service

  web-interface:
    build:
      context: .
      dockerfile: UI/Dockerfile
      args:
        VUE_APP_GATEWAY_URL: https://www.uzorovkirill.ru
    image: cpr-web-ui.cr.cloud.ru/cpr-web-ui:latest
    ports:
      - "8000:8000"
