services:

  db:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: filesdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: uzorov
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  
    entrypoint:
      - /entrypoint.sh


  ai-service:
    build:
      context: .
      dockerfile: ai-service/Dockerfile
    image: uzorovkirill/correct-text-ai:latest
    ports:
      - "84:84"

  document-processing-service:
    build:
      context: .
      dockerfile: document-processing-service/Dockerfile
    image: uzorovkirill/document-processing-service:latest
    ports:
      - "83:83"
    environment:
      POSTGRES_DB: filesdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: uzorov
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      MINIO_HOST: localhost:9000
      MINIO_ACCESS_KEY: UsEr_y8b-DSq-C2K-t32
      MINIO_SECRET_KEY: y8b-DSq-C2K-t32
      HOST_IP: localhost
    depends_on:
      - db


  gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    image: uzorovkirill/api-gateway:latest
    environment:
      - HOST_IP=localhost
      - DOCUMENT_SERVICE_PORT=83
      - TEXT_CORRECTION_SERVICE_PORT=84
    ports:
      - "81:81"
    depends_on:
      - document-processing-service
      - ai-service

  web-interface:
    build:
      context: .
      dockerfile: UI/Dockerfile
      args:
        VUE_APP_GATEWAY_URL: http://localhost:81
    image: cpr-web-ui.cr.cloud.ru/cpr-web-ui:latest
    ports:
      - "8000:8000"
    depends_on:
      - ai-service
      - document-processing-service
      - gateway
