"""Document changed 2 migration

Revision ID: 50aae5492d5b
Revises: d7f00add2de0
Create Date: 2024-08-08 01:20:02.835170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50aae5492d5b'
down_revision: Union[str, None] = 'd7f00add2de0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('subject', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('description', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('status', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('priority', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('registration_date', sa.DateTime(), nullable=True))
    op.drop_column('documents', 'created_at')
    op.drop_column('documents', 'body')
    op.drop_column('documents', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('body', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('documents', 'registration_date')
    op.drop_column('documents', 'priority')
    op.drop_column('documents', 'status')
    op.drop_column('documents', 'description')
    op.drop_column('documents', 'subject')
    # ### end Alembic commands ###
