"""Employee id deleted  migration

Revision ID: fe1cd0ff1743
Revises: 8ffe2674da50
Create Date: 2024-05-21 10:37:01.329937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe1cd0ff1743'
down_revision: Union[str, None] = '8ffe2674da50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'employee_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('employee_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
